[DATABASES]
GAMES1 = 'sqlite+aiosqlite:///database/primary/mount/games.db'
GAMES2 = 'sqlite+aiosqlite:///database/secondary/mount/games.db'
GAMES3 = 'sqlite+aiosqlite:///database/secondary1/mount/games.db'
USERS = 'sqlite+aiosqlite:///database/users.db'

[WORDLE]
MAX_NUM_ATTEMPTS = 6
WORDLE_LENGTH = 5